[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "qwizzy_ai_interview_platform"
version = "0.1.0"
description = "Integrated Interview Intelligence Platform with Teleprompter"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "Frank van Laarhoven" }]
dependencies = []

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
exclude = [
  "*.tests*",
]

[tool.setuptools.package-data]
"*" = [
  "templates/*.html",
  "static/**/*.css",
  "static/**/*.js"
]


